# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm install



pages:
  script:
    - npm run build
    - mkdir public
    - cp dist public -r
  artifacts:
    paths:
      - public
  tags:
    - docker
